java_library (
    name = "queues",
    visibility = ["//visibility:public"],
    srcs = [
        "src/main/java/com/queue/Queue.java",
    ],
    deps = [
        "@interview_prep_array_lib//:arrays",
    ],
)