java_library (
    name = "stacks-lib",
    visibility = ["//visibility:public"],
    srcs = [
        "src/main/java/com/stack/Stack.java",
    ],
    deps = [
        "@interview_prep_array_lib//:arrays",
    ],
)

java_binary (
    name = "stacks-bin",
    srcs = [
        "src/main/java/com/stack/Stack.java",
    ],
    main_class = "Stack",
    deps = [
        "@interview_prep_array_lib//:arrays",
    ],
)