java_library (
    name = "trees-lib",
    visibility = ["//visibility:public"],
    srcs = [
        "src/main/java/com/tree/Tree.java",
    ],
    deps = [
        "@interview_prep_array_lib//:arrays",
    ],
)

java_binary (
    name = "trees-bin",
    srcs = [
        "src/main/java/com/stack/Tree.java",
    ],
    main_class = "Tree",
    deps = [
        "@interview_prep_array_lib//:arrays",
    ],
)